openapi: '3.0.3'
info:
  title: Node API 2024
  version: '1.0'
servers:
  - url: http://localhost:3000

tags:
  - name: Admin
    description: Admin-related operations
  - name: Demo
    description: Demo routes for testing and examples
  - name: System
    description: System-related operations

paths:
  /api/admin:
    get:
      summary: Get admin welcome message
      tags:
        - Admin
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Hello, world!'

  /api/admin/login:
    post:
      summary: Admin login
      tags:
        - Admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Unauthorized

  /api/admin/demo:
    get:
      summary: Access demo route
      tags:
        - Demo
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Demo route accessed'
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                        example: 'Hi'

  /api/admin/demo/error:
    get:
      summary: Trigger a demo error
      tags:
        - Demo
      security:
        - BearerAuth: []
      responses:
        '500':
          description: Internal Server Error

  /api/admin/demo/get-user:
    get:
      summary: Get user information
      tags:
        - Demo
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: string
                  role:
                    type: string

  /ping:
    get:
      summary: Ping the server
      tags:
        - System
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
                example: 'pong'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
